packages:
  - packages/*

catalog:
  '@babel/types': ^7.28.5
  '@elora-cloud/elora-cli': ^1.0.15
  '@elora-cloud/eslint-config': ^6.2.0
  '@interactjs/actions': ^1.10.27
  '@interactjs/auto-scroll': ^1.10.27
  '@interactjs/auto-start': ^1.10.27
  '@interactjs/core': ^1.10.27
  '@interactjs/dev-tools': ^1.10.27
  '@interactjs/interact': ^1.10.27
  '@interactjs/modifiers': ^1.10.27
  '@interactjs/utils': ^1.10.27
  '@types/element-resize-detector': ^1.1.6
  '@types/jest': ^30.0.0
  '@types/node': ^24.10.1
  '@vitejs/plugin-vue': ^6.0.2
  '@vitest/coverage-v8': ^4.0.14
  '@vue/language-core': ^3.1.5
  '@vue/test-utils': ^2.4.6
  cross-env: ^10.1.0
  echarts: ^6.0.0
  element-resize-detector: ^1.2.4
  eslint: ^9.39.1
  interactjs: ^1.10.27
  jsdom: ^27.2.0
  mitt: ^3.0.1
  prettier: ^3.6.2
  sass: ^1.94.2
  stylelint: ^16.26.0
  stylelint-config-recommended: ^17.0.0
  stylelint-config-recommended-vue: ^1.6.1
  stylelint-config-standard: ^39.0.1
  stylelint-config-standard-scss: ^16.0.0
  typescript: ^5.9.3
  unplugin-dts: 1.0.0-beta.6
  vite: ^7.2.4
  vitest: ^4.0.14
  vue: ^3.5.25
  vue-tsc: ^3.1.5
