packages:
  - packages/*
catalog:
  '@babel/types': ^7.27.0
  '@elora-cloud/elora-cli': ^1.0.14
  '@elora-cloud/eslint-config': ^4.5.1
  '@interactjs/actions': ^1.10.27
  '@interactjs/auto-scroll': ^1.10.27
  '@interactjs/auto-start': ^1.10.27
  '@interactjs/core': ^1.10.27
  '@interactjs/dev-tools': ^1.10.27
  '@interactjs/interact': ^1.10.27
  '@interactjs/modifiers': ^1.10.27
  '@interactjs/utils': ^1.10.27
  '@types/element-resize-detector': ^1.1.6
  '@types/jest': ^29.5.14
  '@types/node': ^22.14.1
  '@vitejs/plugin-vue': ^5.2.3
  '@vitest/coverage-v8': ^3.1.1
  '@vue/test-utils': ^2.4.6
  ant-design-vue: ^4.2.6
  cross-env: ^7.0.3
  echarts: ^5.6.0
  element-resize-detector: ^1.2.4
  eslint: ^9.25.0
  interactjs: ^1.10.27
  jsdom: ^26.1.0
  mitt: ^3.0.1
  prettier: ^3.5.3
  sass: ^1.86.3
  stylelint: ^16.18.0
  stylelint-config-recommended: ^16.0.0
  stylelint-config-recommended-vue: ^1.6.0
  stylelint-config-standard: ^38.0.0
  stylelint-config-standard-scss: ^14.0.0
  typescript: ^5.8.3
  uuid: ^11.1.0
  vite: ^6.3.2
  vite-plugin-dts: ^4.5.3
  vitest: ^3.1.1
  vue: ^3.5.13
  vue-template-compiler: ^2.7.16
  vue-tsc: ^2.2.8
