shellEmulator: true

trustPolicy: no-downgrade

packages:
  - packages/*

catalog:
  '@babel/types': ^7.29.0
  '@elora-cloud/elora-cli': ^1.0.16
  '@elora-cloud/eslint-config': ^7.6.0
  '@elora-cloud/unplugin-dts': 1.0.0-beta.7
  '@interactjs/actions': ^1.10.27
  '@interactjs/auto-scroll': ^1.10.27
  '@interactjs/auto-start': ^1.10.27
  '@interactjs/core': ^1.10.27
  '@interactjs/dev-tools': ^1.10.27
  '@interactjs/interact': ^1.10.27
  '@interactjs/modifiers': ^1.10.27
  '@interactjs/utils': ^1.10.27
  '@types/element-resize-detector': ^1.1.6
  '@types/jest': ^30.0.0
  '@types/node': ^25.5.0
  '@types/rimraf': ^4.0.5
  '@vitejs/plugin-vue': ^6.0.5
  '@vitest/coverage-v8': ^4.1.0
  '@vue/language-core': ^3.2.5
  '@vue/test-utils': ^2.4.6
  cross-env: ^10.1.0
  echarts: ^6.0.0
  element-resize-detector: ^1.2.4
  eslint: ^10.0.3
  interactjs: ^1.10.27
  jsdom: ^29.0.0
  mitt: ^3.0.1
  prettier: ^3.8.1
  rimraf: ^6.1.3
  sass: ^1.98.0
  stylelint: ^17.4.0
  stylelint-config-recommended: ^18.0.0
  stylelint-config-recommended-vue: ^1.6.1
  stylelint-config-standard: ^40.0.0
  stylelint-config-standard-scss: ^17.0.0
  typescript: ^5.9.3
  vite: ^8.0.0
  vitest: ^4.1.0
  vue: ^3.5.30
  vue-tsc: ^3.2.5
