packages:
  - packages/*
catalog:
  '@babel/types': ^7.28.0
  '@elora-cloud/elora-cli': ^1.0.14
  '@elora-cloud/eslint-config': ^4.16.2
  '@interactjs/actions': ^1.10.27
  '@interactjs/auto-scroll': ^1.10.27
  '@interactjs/auto-start': ^1.10.27
  '@interactjs/core': ^1.10.27
  '@interactjs/dev-tools': ^1.10.27
  '@interactjs/interact': ^1.10.27
  '@interactjs/modifiers': ^1.10.27
  '@interactjs/utils': ^1.10.27
  '@types/element-resize-detector': ^1.1.6
  '@types/jest': ^30.0.0
  '@types/node': ^24.0.10
  '@vitejs/plugin-vue': ^6.0.0
  '@vitest/coverage-v8': ^3.2.4
  '@vue/test-utils': ^2.4.6
  cross-env: ^7.0.3
  echarts: ^5.6.0
  element-resize-detector: ^1.2.4
  eslint: ^9.30.1
  interactjs: ^1.10.27
  jsdom: ^26.1.0
  mitt: ^3.0.1
  prettier: ^3.6.2
  sass: ^1.89.2
  stylelint: ^16.21.1
  stylelint-config-recommended: ^16.0.0
  stylelint-config-recommended-vue: ^1.6.1
  stylelint-config-standard: ^38.0.0
  stylelint-config-standard-scss: ^15.0.1
  typescript: ^5.8.3
  unplugin-dts: 1.0.0-beta.2
  vite: ^7.0.2
  vitest: ^3.2.4
  vue: ^3.5.17
  vue-tsc: ^3.0.1
